ccflags-y += -Idrivers/media/platform/msm/camera_v2-legacy
ccflags-y += -Idrivers/media/platform/msm/camera_v2-legacy/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2-legacy/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2-legacy/common
obj-$(CONFIG_MSM_CPP) += msm_cpp_soc.o msm_cpp.o
